sudo: false

language: python

python:
  - '2.7'
  - '3.3'
  - pypy

before_install:
  - pip install flake8 hacking
  - flake8 .

install:
  - python setup.py install

script:
  - gotenshita
  - gotenshita --show-past
  - gotenshita --tomorrow
  - gotenshita a,f
