sudo: false

cache:
  - pip

language: python

python:
  - '2.7'
  - '3.3'
  - pypy

install:
  - python setup.py install

before_script:
  - pip install flake8 hacking
  - flake8 .

script:
  - gotenshita
  - gotenshita --show-past
  - gotenshita --tomorrow
  - gotenshita a,f
